import type { Metadata } from "next";
import { ConvexClientProvider } from "./ConvexClientProvider";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/themeToggle";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      
      <header className="">
      <Link href='/' className="m-2">Dashboard</Link>
      <Link href='/users' className="m-2">Users</Link>
      <Link href='/about' className="m-2">About</Link>
      <ModeToggle/>
      </header>

      <main>
      <ConvexClientProvider>{children}</ConvexClientProvider>
      <Toaster position="bottom-right" /> 
      </main>

    <footer className="mt-10">
      footer
    </footer>
    </ThemeProvider>
    </body>
    </html>
  );
}
